//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int id_company { get; set; }
        public string full_name { get; set; }
        public string short_name { get; set; }
        public string activity_type { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string payer_account_number { get; set; }
        public int id_director { get; set; }
        public int id_ownership_type { get; set; }
        public int id_accountant { get; set; }
        public int id_address { get; set; }
        public int id_bank { get; set; }
        public int id_contact { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual BankDetails BankDetails { get; set; }
        public virtual ChiefAccountant ChiefAccountant { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual Director Director { get; set; }
        public virtual OwnershipType OwnershipType { get; set; }
    }
}
